project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "Demetris Charalambous"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - href: tab-visualization/visualization-index.qmd
        text: Visualization
      - href: tab-presentation/presentation-index.qmd
        text: Presentation
      - href: tab-analysis/analysis-index.qmd
        text: Analysis
      - href: tab-survey/survey-index.qmd
        text: Survey
      - href: tab-contact/contact-index.qmd
        text: Contact
        
    logo: images/logo_tepak.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

