{
  "hash": "4ee3ac30e08345bcf1cc7c078d1c590b",
  "result": {
    "engine": "knitr",
    "markdown": "# Digital Habits & Screen Time Survey Report\n\n## Starting Point\n\n\n\n```{=html}\n<style>\n  .video-wrapper {\n    position: relative;\n    width: 100%;\n    padding-top: 56.25%;\n    margin: 20px 0;\n  }\n  .video-wrapper iframe {\n    position: absolute;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    border: none;\n  }\n</style>\n<div class=\"video-wrapper\">\n  <iframe title=\"Digital Habits Survey Video\"\n    src=\"https://www.youtube.com/embed/W6CBb3yX9Zs\" \n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n    allowfullscreen>\n  </iframe>\n</div>\n```\n\n\n\n\n## Overview\nThis report summarizes the synthetic data generated from our \"Digital Habits & Screen Time Survey\". It includes summary statistics and visualizations that reflect digital habits across different demographics.\n\n## Data Summary  \n*Screen Time Scale*:  \n1 = Less than 2 hours, 5 = More than 8 hours  \n*Phone Anxiety Scale*:  \n1 = Strongly disagree, 5 = Strongly agree  \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Summary Statistics by Age Group\n\n| Age_Group | Avg. Screen Time (1-5) | Avg. Phone Anxiety (1-5) |\n|:---------:|:----------------------:|:------------------------:|\n| Under 18  |          4.21          |           4.41           |\n|   18-24   |          3.87          |           4.62           |\n|   25-34   |          2.82          |           3.32           |\n|   35-44   |          2.81          |           3.45           |\n|   45-54   |          1.88          |           2.29           |\n|   55-64   |          1.73          |           2.27           |\n|    65+    |          2.00          |           1.67           |\n\n\n:::\n:::\n\n\n\n\n## Interpretation\n**1. Younger age groups spend significantly more time on screens and experience higher phone-related anxiety.**\n\nThe Under 18 group reports the highest screen time (4.21) and phone anxiety (4.41), suggesting a strong dependency on digital devices.\nThe 18-24 group follows closely, with slightly less screen time (3.87) but the highest phone anxiety (4.62), indicating heightened stress or attachment to their phones.\n\n**2. Screen time and phone anxiety gradually decrease with age.**\n\nThe 25-34 and 35-44 age groups show a notable drop in screen time (2.82 and 2.81, respectively) and phone anxiety (3.32 and 3.45). This suggests a more balanced relationship with technology compared to younger users.\n\n**3. Older adults (45+) use screens the least and report the lowest phone anxiety.**\n\nThe 45-54 and 55-64 groups show further declines in screen time (1.88 and 1.73) and anxiety (2.29 and 2.27).\nThe 65+ group has the lowest values for both (2.00 screen time, 1.67 phone anxiety), indicating that they may use phones more functionally rather than habitually or emotionally.\n\n## Conclusion\nThe data highlights a strong correlation between age, screen time, and phone anxiety. Younger individuals—especially those under 25—spend the most time on screens and report the highest levels of anxiety related to phone use. As people age, both metrics steadily decline, suggesting that older users may have a more controlled or less emotionally attached relationship with their devices.\n\n## Gallery\n\n\n\n```{=html}\n<div class=\"iframe-container\">\n  <iframe \n    src=\"https://albumizr.com/a/QecM\"\n    scrolling=\"no\"\n    frameborder=\"0\"\n    allowfullscreen\n    style=\"border: none;\"\n  ></iframe>\n</div>\n\n<style>\n.iframe-container {\n  position: relative;\n  width: 100%;\n  padding-top: 57.14%;\n  margin: 20px 0;\n  overflow: hidden;\n}\n\n.iframe-container iframe {\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n}\n</style>\n```",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}